addr/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.name_list, name='name_list'),
url(r'^name/(?P<pk>\d+)/$', views.name_detail, name='name_detail'),
url(r'^name/new/$', views.name_new, name='name_new'),
url(r'^name/(?P<pk>\d+)/edit/$', views.name_edit, name='name_edit'),
url(r'^drafts/$', views.name_draft_list, name='name_draft_list'),
url(r'^name/(?P<pk>\d+)/publish/$', views.name_publish, name='name_publish'),
url(r'^name/(?P<pk>\d+)/remove/$', views.name_remove, name='name_remove'),
url(r'^name/(?P<pk>\d+)/approve/$', views.name_approve, name='name_approve'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/login/$', views.login, name='login'),
url(r'^accounts/logout/$', views.logout, name='logout', kwargs={'next_page': '/'}),
    url(r'', include('addr.urls', namespace='addr')),
]

addr/models.py
from django.db import models
from django.utils import timezone


class Addr(models.Model):
    name = models.CharField(max_length=30, blank=True)
    phone1 = models.CharField(max_length=15)
    phone2 = models.CharField(max_length=15, blank=True)
    email = models.EmailField(max_length=70, blank=True)
    created_date = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    # approved_addr = models.BooleanField(default=False)
    published_date = models.DateTimeField(blank=True, null=True)
    # title = models.CharField(max_length=200)
    # text = models.TextField()
    # on_off = models.NullBooleanField(default=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    # def approve(self):
    #     self.approved_addr = True
    #     self.save()

    def __str__(self):
        return self.name

addr/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from addr.form import AddrForm
from .models import Addr


def name_list(request):
    names = Addr.objects.all().order_by('name')
    return render(request, "addr/name_list.html", {'names': names})

@login_required
def name_detail(request, pk):
    name = get_object_or_404(Addr, pk=pk)
    return render(request, 'addr/name_detail.html', {'name': name})

@login_required
def name_new(request):
    if request.method == "POST":
        form = AddrForm(request.POST)
        if form.is_valid():
            name = form.save(commit=False)
            # name.author = request.user
            name.created_date = timezone.now()
            name.save()
            return redirect('addr:name_detail', pk=name.pk)
    else:
        form = AddrForm()
    return render(request, 'addr/name_edit.html', {'form': form})

@login_required
def name_edit(request, pk):
    name = get_object_or_404(Addr, pk=pk)
    if request.method == "POST":
        form = AddrForm(request.POST, instance=name)
        if form.is_valid():
            name = form.save(commit=False)
            # post.author = request.user
            name.created_date = timezone.now()
            name.save()
            return redirect('addr:name_detail', pk=name.pk)
    else:
        form = AddrForm(instance=name)
    return render(request, 'addr/name_edit.html', {'form': form})

@login_required
def name_draft_list(request):
    names = Addr.objects.all().order_by('name')
    return render(request, 'addr/name_draft_list.html', {'names': names})

@login_required
def name_publish(request, pk):
    name = get_object_or_404(Addr, pk=pk)
    name.publish()
    return redirect('addr:name_detail', pk=pk)

@login_required
def name_remove(request, pk):
    name = get_object_or_404(Addr, pk=pk)
    name.delete()
    return redirect('addr:name_list')

@login_required
def name_approve(request, pk):
    name = get_object_or_404(Addr, pk=pk)
    name.approve()
    return redirect('addr:name_detail', pk=name.pk)

addr/templates/addr/base.html
{% load staticfiles %}
<html>
    <head>
        <title>Django Girls blog</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
        <link rel="stylesheet" href="{% static 'css/addr.css' %}">
    </head>
<body>
<div class="page-header">
     {% if user.is_authenticated %}
    <a href="{% url 'addr:name_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
    <a href="{% url 'addr:name_draft_list' %}" class="top-menu"><span class="glyphicon glyphicon-edit"></span></a>
     <p class="top-menu">Hello {{ user.username }} <small>(<a href="{% url 'logout' %}">Log out</a>)</small></p>
    {% else %}
    <a href="{% url 'login' %}" class="top-menu"><span class="glyphicon glyphicon-lock"></span></a>
    {% endif %}
    <h1><a href="/">주소록 ADDR</a></h1>
</div>
<div class="content container">
    <div class="row">
        <div class="col-md-8">
{% block content %}
            {% endblock %}
     </div>
    </div>
</div>
</body>
</html>

addr/templates/addr/name_detail.html
{% extends 'addr/base.html' %}

{% block content %}
    <div class="post">
         {% if name.created_date %}
            <div class="date">
                {{ name.created_date }}
            </div>
        <a class="btn btn-default" href="{% url 'addr:name_publish' pk=name.pk %}">Publish</a>
        <!--<a class="btn btn-default" href="{% url 'addr:name_approve' pk=name.pk %}"><span class="glyphicon glyphicon-ok"></span></a>-->
        {% endif %}
        <a class="btn btn-default" href="{% url 'addr:name_remove' pk=name.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
        <a class="btn btn-default" href="{% url 'addr:name_edit' pk=name.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>

        <h1>{{ name.name }}</h1>

        <p1>전화1:{{ name.phone1  }}</p1>
        <br>
        <p1>전화2:{{ name.phone2 }}</p1>
        <br>
        <p1>@메일:{{ name.email }}</p1>
    </div>
{% endblock %}

addr/templates/addr/name_draft_list.html
{% extends 'addr/base.html' %}

{% block content %}
    {% for name in names %}
        <div class="post">
            <p class="date">created: {{ name.created_date|date:'d-m-Y' }}</p>
            <h1><a href="{% url 'addr:name_detail' pk=name.pk %}">{{ name.name }}</a></h1>
            <p>{{ name.phone1|truncatechars:200 }}</p>
        </div>
    {% endfor %}
{% endblock %}

addr/templates/addr/name_edit.html
{% extends 'addr/base.html' %}

{% block content %}
    <h1>New Addr</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

addr/templates/addr/name_list.html
{% extends 'addr/base.html' %}

{% block content %}
{% for name in names.all %}
    <div class="post">
    {% if user.is_authenticated or name.published_date %}
            {% if not name.published_date %}
            {% endif %}
        <h1><a href="{% url 'addr:name_detail' pk=name.pk %}">{{ name.name }}</a></h1>
        <p1>전화1:{{ name.phone1 }}</p1>
        <br>
        <p1>전화2:{{ name.phone2 }}</p1>
        <br>
        <p1>@메일:{{ name.email }}</p1>

    </div>
{% endif %}
{% empty %}
{% endfor %}

{% endblock %}